Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/02/2022
Var
// Seção de Declarações das variáveis 
   A, X: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Escreva("Digite um número negativo: ")
   Leia(X)
   A <- Abs(X)
   Escreva("Res: ", A)


Fimalgoritmo